name: IslandSMP
version: '${version}'
main: lol.maltest.islandsmp.IslandSMP
api-version: '1.20'
author: maltest
website: https://maltest.org
depend: ["FastAsyncWorldEdit", "WorldBorderAPI", "Citizens"]